server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://43.143.231.162:3306/answerly?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 72232b47-815b-4e27-9df7-9e590ca32b71
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  application:
    name: answerly

  data:
    redis:
      host: 43.143.231.162
      port: 6379
      password: 18747796-f035-4bb3-b51c-f8ac64890aea

  elasticsearch:
    username: elastic
    password: elastic

  mail:
    protocol: smtps
    host: smtp.163.com
    port: 465
    username: buaa_yzd@163.com
    password: RBdFP4r9FfXcJazi
    default-encoding: UTF-8
    from: buaa_yzd@163.com
    properties:
      mail.smtp.socketFactoryClass: javax.net.ssl.SSLSocketFactory

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

flow-limit:
  enable: true
  time-window: 1
  max-access-count: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

elasticsearch:
  host: 43.143.231.162
  index-name: question

tencent:
  cos:
    secretId: AKIDiRxGMNDpHWZN3YrxqWzEH71zysgJjdPz
    secretKey: Vo177vX6XovzxISSF9rMfldHjy61iEJS
    region: ap-beijing
    bucketName: yuanzhida-cos-1352975306


